AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FrankleWordsService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for Frankle"
    Properties:
      Name: "frankle-words-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://frankle.phil-code.com'" # replace with frontend app URL

  FrankleWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
        - DynamoDBCrudPolicy:
            TableName: !Ref FrankleWordsTable
      Events:
        WordsOptions:
          Type: Api
          Properties:
            Path: /words
            Method: OPTIONS
            RestApiId: !Ref FrankleWordsService
        GetRandomWord:
          Type: Api
          Properties:
            Path: /words/random
            Method: GET
            RestApiId: !Ref FrankleWordsService
        CheckWord:
          Type: Api
          Properties:
            Path: /words/check/{word}
            Method: GET
            RestApiId: !Ref FrankleWordsService
    Metadata:
      BuildMethod: makefile

  FrankleWordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FrankleWords
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
